services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: hrpass
      POSTGRES_DB: hriq
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  minio:
    image: bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio:/data
  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Admin123!@#
    ports: ["9200:9200"]
  api:
    build: ./apps/gateway
    env_file: .env
    depends_on: [postgres, redis, minio, opensearch]
    ports: ["8080:8080"]
  frontend:
    build:
      context: ./web/frontend
      args:
        VITE_API_BASE: http://localhost:8080
    environment:
      - VITE_API_BASE=http://localhost:8080
    ports: ["3000:3000"]
volumes:
  pgdata:
  minio:
